const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function harness(){
 const nodes=new Map();const make=()=>({value:'',children:[],append(e){this.children.push(e);if(this.value===''&&e.value!==undefined)this.value=String(e.value)},replaceChildren(){this.children=[];this.value=''},removeAttribute(k){delete this[k]}});const el=id=>{if(!nodes.has(id))nodes.set(id,make());return nodes.get(id)};
 const entries=[{entry_id:'text',source_text:'<script>literal</script>',search_heading:'Safety note',doc_items:['#/texts/1'],page_numbers:[1],evidence_types:['note']},{entry_id:'picture',source_text:'Diagram caption',doc_items:['#/pictures/2'],page_numbers:[2]}];
 vm.runInNewContext(fs.readFileSync('app/static/technical-evidence.js','utf8'),{document:{getElementById:el,createElement:make},fetch:async url=>({ok:true,json:async()=>url==='/api/retrieval/status'?{books:[{postprocess_job_id:25,source_filename:'Manual',index_ready:true}]}:{ready:true,stage3_available:true,entries,candidate_counts:{detected:2,picture_linked:1}}})});return el;
}
const settle=()=>new Promise(r=>setImmediate(r));
test('text and picture candidates both load; literal source is visible without inference',async()=>{const el=harness();await settle();assert.equal(el('entry').children.length,2);assert.equal(el('candidate-preview').hidden,false);assert.equal(el('candidate-text').textContent,'<script>literal</script>');assert.equal(el('extract').disabled,true);assert.equal(el('candidate-image').hidden,true);assert.equal(el('candidate-pages').children[0].href,'/docling-review?job=25&page=1');});
test('selecting picture enables extraction and shows original crop before inference',async()=>{const el=harness();await settle();el('entry').value='picture';el('entry').onchange();assert.equal(el('extract').disabled,false);assert.equal(el('candidate-image').src,'/api/postprocess/jobs/25/picture/2');assert.equal(el('candidate-image').hidden,false);el('entry').value='text';el('entry').onchange();assert.equal(el('extract').disabled,true);assert.equal(el('candidate-image').src,undefined);});
test('next action explains text versus diagram and confirmation starts disabled',async()=>{const el=harness();await settle();assert.match(el('next-step').textContent,/text or table/);assert.equal(el('validate').disabled,true);el('entry').value='picture';el('entry').onchange();assert.match(el('next-step').textContent,/Read this diagram with AI/);assert.equal(el('validate').disabled,true);});
test('page provides beginner guidance and hides raw data in Advanced',()=>{const html=fs.readFileSync('app/static/technical-evidence.html','utf8');assert.match(html,/What can I do here/);assert.match(html,/What you get/);assert.match(html,/<summary>Advanced: edit diagram data<\/summary>/);assert.match(html,/id="graph-readable"/);assert.match(html,/Confirm this matches the original/);});
